// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 02 Jul 2025 23:31:51 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

int TIndexCallback_6d729b4e(long int Current, long int Total, void* ICPrivate) {
	return tIndexCallback6D729B4E(Current, Total, ICPrivate);
}

