// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 02 Jul 2025 23:31:51 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package ffms_bindings

/*
#cgo pkg-config: ffms2
#include "ffms.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// ErrorInfo as declared in include/ffms.h:94
type ErrorInfo struct {
	ErrorType      int32
	SubType        int32
	BufferSize     int32
	Buffer         []byte
	ref43ef05fa    *C.FFMS_ErrorInfo
	allocs43ef05fa interface{}
}

// VideoSource as declared in include/ffms.h:96
type VideoSource C.FFMS_VideoSource

// AudioSource as declared in include/ffms.h:97
type AudioSource C.FFMS_AudioSource

// Indexer as declared in include/ffms.h:98
type Indexer C.FFMS_Indexer

// Index as declared in include/ffms.h:99
type Index C.FFMS_Index

// Track as declared in include/ffms.h:100
type Track C.FFMS_Track

// ResampleOptions as declared in include/ffms.h:306
type ResampleOptions struct {
	ChannelLayout          int64
	SampleFormat           SampleFormat
	SampleRate             int32
	MixingCoefficientType  MixingCoefficientType
	CenterMixLevel         float64
	SurroundMixLevel       float64
	LFEMixLevel            float64
	Normalize              int32
	ForceResample          int32
	ResampleFilterSize     int32
	ResamplePhaseShift     int32
	LinearInterpolation    int32
	CutoffFrequencyRatio   float64
	MatrixedStereoEncoding MatrixEncoding
	FilterType             ResampleFilterType
	KaiserBeta             int32
	DitherMethod           AudioDitherMethod
	ref2fdbecca            *C.FFMS_ResampleOptions
	allocs2fdbecca         interface{}
}

// Frame as declared in include/ffms.h:347
type Frame struct {
	Data                         [4]*byte
	Linesize                     [4]int32
	EncodedWidth                 int32
	EncodedHeight                int32
	EncodedPixelFormat           int32
	ScaledWidth                  int32
	ScaledHeight                 int32
	ConvertedPixelFormat         int32
	KeyFrame                     int32
	RepeatPict                   int32
	InterlacedFrame              int32
	TopFieldFirst                int32
	PictType                     byte
	ColorSpace                   int32
	ColorRange                   int32
	ColorPrimaries               int32
	TransferCharateristics       int32
	ChromaLocation               int32
	HasMasteringDisplayPrimaries int32
	MasteringDisplayPrimariesX   [3]float64
	MasteringDisplayPrimariesY   [3]float64
	MasteringDisplayWhitePointX  float64
	MasteringDisplayWhitePointY  float64
	HasMasteringDisplayLuminance int32
	MasteringDisplayMinLuminance float64
	MasteringDisplayMaxLuminance float64
	HasContentLightLevel         int32
	ContentLightLevelMax         uint32
	ContentLightLevelAverage     uint32
	DolbyVisionRPU               []byte
	DolbyVisionRPUSize           int32
	HDR10Plus                    []byte
	HDR10PlusSize                int32
	ref32c01ffc                  *C.FFMS_Frame
	allocs32c01ffc               interface{}
}

// TrackTimeBase as declared in include/ffms.h:352
type TrackTimeBase struct {
	Num            int64
	Den            int64
	refff11a159    *C.FFMS_TrackTimeBase
	allocsff11a159 interface{}
}

// FrameInfo as declared in include/ffms.h:359
type FrameInfo struct {
	PTS            int64
	RepeatPict     int32
	KeyFrame       int32
	OriginalPTS    int64
	refb35c55f5    *C.FFMS_FrameInfo
	allocsb35c55f5 interface{}
}

// VideoProperties as declared in include/ffms.h:397
type VideoProperties struct {
	FPSDenominator               int32
	FPSNumerator                 int32
	RFFDenominator               int32
	RFFNumerator                 int32
	NumFrames                    int32
	SARNum                       int32
	SARDen                       int32
	CropTop                      int32
	CropBottom                   int32
	CropLeft                     int32
	CropRight                    int32
	TopFieldFirst                int32
	ColorSpace                   int32
	ColorRange                   int32
	FirstTime                    float64
	LastTime                     float64
	Rotation                     int32
	Stereo3DType                 int32
	Stereo3DFlags                int32
	LastEndTime                  float64
	HasMasteringDisplayPrimaries int32
	MasteringDisplayPrimariesX   [3]float64
	MasteringDisplayPrimariesY   [3]float64
	MasteringDisplayWhitePointX  float64
	MasteringDisplayWhitePointY  float64
	HasMasteringDisplayLuminance int32
	MasteringDisplayMinLuminance float64
	MasteringDisplayMaxLuminance float64
	HasContentLightLevel         int32
	ContentLightLevelMax         uint32
	ContentLightLevelAverage     uint32
	Flip                         int32
	ref60a9254b                  *C.FFMS_VideoProperties
	allocs60a9254b               interface{}
}

// AudioProperties as declared in include/ffms.h:410
type AudioProperties struct {
	SampleFormat   int32
	SampleRate     int32
	BitsPerSample  int32
	Channels       int32
	ChannelLayout  int64
	NumSamples     int64
	FirstTime      float64
	LastTime       float64
	LastEndTime    float64
	reff68755de    *C.FFMS_AudioProperties
	allocsf68755de interface{}
}

// KeyValuePair as declared in include/ffms.h:415
type KeyValuePair struct {
	Key            []byte
	Value          []byte
	refb4378ab6    *C.FFMS_KeyValuePair
	allocsb4378ab6 interface{}
}

// TIndexCallback type as declared in include/ffms.h:417
type TIndexCallback func(current int64, total int64, iCPrivate unsafe.Pointer) int32
